"""suppression removal history

Revision ID: 2882d8b31510
Revises: 3f6a4a006b56
Create Date: 2026-08-05 18:05:46.401952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2882d8b31510'
down_revision = '3f6a4a006b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('removed_by_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_suppressions_removed_by_id_users', 'users', ['removed_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_suppressions_removed_by_id_users', type_='foreignkey')
        batch_op.drop_column('removed_by_id')
        batch_op.drop_column('removed_at')

    # ### end Alembic commands ###
