"""production data model

Revision ID: 3f6a4a006b56
Revises:
Create Date: 2026-08-05 17:54:41.480329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6a4a006b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verification_cache',
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    with op.batch_alter_table('verification_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('upload_path', sa.String(length=1000), nullable=True),
    sa.Column('email_column', sa.String(length=255), nullable=True),
    sa.Column('name_column', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('tested_hash', sa.String(length=64), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('suppressed_count', sa.Integer(), nullable=False),
    sa.Column('failure_summary', sa.String(length=1000), nullable=True),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_state'), ['state'], unique=False)

    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('updated_by_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('result_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action', 'key', name='uq_idempotency')
    )
    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('campaign_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('original_email', sa.String(length=1000), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('recipient_name', sa.String(length=500), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('send_status', sa.String(length=32), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'normalized_email', name='uq_campaign_recipient')
    )
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_recipients_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_normalized_email'), ['normalized_email'], unique=False)

    op.create_table('suppressions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_campaign_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressions_normalized_email'), ['normalized_email'], unique=True)

    op.create_table('template_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('storage_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_name')
    )
    with op.batch_alter_table('template_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_assets_template_id'), ['template_id'], unique=False)

    op.create_table('validation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('policy', sa.String(length=16), nullable=False),
    sa.Column('smtp_enabled', sa.Boolean(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('problematic_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rq_job_id')
    )
    with op.batch_alter_table('validation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_jobs_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_jobs_campaign_id'))

    op.drop_table('validation_jobs')
    with op.batch_alter_table('template_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_assets_template_id'))

    op.drop_table('template_assets')
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressions_normalized_email'))

    op.drop_table('suppressions')
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_normalized_email'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_campaign_id'))

    op.drop_table('campaign_recipients')
    op.drop_table('oauth_credentials')
    op.drop_table('idempotency_keys')
    op.drop_table('email_templates')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_state'))
        batch_op.drop_index(batch_op.f('ix_campaigns_owner_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('verification_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_cache_expires_at'))

    op.drop_table('verification_cache')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
